export const CATEGORIES = {
  orchestration: { key: 'orchestration', label: '编排与控制', color: '#3b82f6' },
  memory: { key: 'memory', label: '记忆与上下文', color: '#8b5cf6' },
  knowledge: { key: 'knowledge', label: '知识与检索', color: '#0ea5e9' },
  tools: { key: 'tools', label: '工具与集成', color: '#10b981' },
  reasoning: { key: 'reasoning', label: '推理与规划', color: '#f59e0b' },
  reliability: { key: 'reliability', label: '可靠性', color: '#ef4444' },
  safety: { key: 'safety', label: '安全与护栏', color: '#14b8a6' },
  observability: { key: 'observability', label: '可观测性', color: '#6366f1' },
  delivery: { key: 'delivery', label: '交付与体验', color: '#ec4899' },
};

export const DIMENSIONS = {
  architecture: { key: 'architecture', label: '架构完整度', weight: 0.2 },
  reasoning: { key: 'reasoning', label: '推理与规划', weight: 0.14 },
  memory: { key: 'memory', label: '记忆与上下文', weight: 0.13 },
  tools: { key: 'tools', label: '工具编排', weight: 0.13 },
  knowledge: { key: 'knowledge', label: '知识增强', weight: 0.1 },
  reliability: { key: 'reliability', label: '可靠性', weight: 0.14 },
  safety: { key: 'safety', label: '安全护栏', weight: 0.08 },
  observability: { key: 'observability', label: '可观测性', weight: 0.05 },
};

const p = (source, label) => ({
  source,
  flags: 'i',
  label: label ?? source.slice(0, 24),
});

export const CAPABILITIES = [
  {
    id: 'agent_loop',
    label: 'Agent 主循环',
    en: 'Agent Loop / ReAct Loop',
    category: 'orchestration',
    dimension: 'architecture',
    weight: 10,
    headline: '让模型反复「思考 → 调用工具 → 观察结果」直到任务完成的核心控制结构。',
    detail: '识别依据：存在迭代执行的控制结构（while / for + 状态推进），或显式的 step / iteration / max_turns 预算变量，或 ReAct 风格的 Thought-Action-Observation 提示词。',
    patterns: [
      p(p0('(?:while|for)\\s*\\(?\\s*(?:True\\b|true\\b|1\\s*[:)]|not\\s+\\w+|\\w+\\s*(?:<|!=|!==))'), '循环条件推进'),
      p(p0('\\b(?:max_(?:iterations|steps|turns|loops|rounds)|maxIterations|maxSteps|maxTurns|maxRounds)\\b'), '循环预算上限'),
      p(p0('\\b(?:agent|run|execute|invoke|react|agentic)[_ ]?(?:loop|iteration)|loop[_ ]?(?:count|index|steps)|iteration\\s*[=+]'), '显式 agent loop 命名'),
      p(p0('\\b(?:Thought|Observation)\\s*[:<\\[]'), 'ReAct 结构'),
      p(p0('\\b(?:step|turn|round)\\s*(?:\\+\\+|\\+=|<|<=)\\s*'), '步数递增控制'),
    ],
    docPatterns: [p(p0('agent\\s*loop|react\\s*loop|agentic\\s*loop|主循环|循环执行'))],
    tags: ['Loop', 'ReAct', '控制流'],
  },
  {
    id: 'short_term_memory',
    label: '短期记忆（会话历史）',
    en: 'Conversation Memory',
    category: 'memory',
    dimension: 'memory',
    weight: 9,
    headline: '把多轮对话消息按顺序累积并回传给模型，是 Agent 具备上下文连续性的最低门槛。',
    detail: '识别依据：维护 messages / history / conversation 列表，并在每次调用模型时把历史一并传入。',
    patterns: [
      p(p0('\\b(?:messages|history|conversation|chat_history|chatHistory|dialog|context_window)\\b\\s*(?:[:=]|\\.(?:push|append|extend|add|concat))'), '历史容器'),
      p(p0('\\.(?:addMessage|appendMessage|addMessages|add_user_message|add_ai_message|withMessages)\\s*\\('), '消息追加 API'),
      p(p0('(?:role|message_type|msg_role|sender|speaker)["\'`]?\\s*[:=]\\s*["\'`](?:user|human|assistant|ai|bot|tool|system)'), '角色消息体'),
      p(p0('MemoryWindow|ConversationBufferWindowMemory|ConversationMemory|\\bmemory\\b.*\\b(?:window|buffer|history)'), '记忆组件'),
    ],
    docPatterns: [p(p0('短期记忆|会话历史|conversation memory|chat history'))],
    tags: ['Memory', 'Session'],
  },
  {
    id: 'long_term_memory',
    label: '长期记忆',
    en: 'Long-term Memory',
    category: 'memory',
    dimension: 'memory',
    weight: 8,
    headline: '跨会话持久化的事实/偏好/经验存储，通常配合向量或键值检索召回。',
    detail: '识别依据：存在 memory store / recall / persist 语义，或把记忆写入数据库、文件、向量库以便下次会话取回。',
    patterns: [
      p(p0('\\b(?:long_term_memory|longTermMemory|persistentMemory|episodicMemory|semanticMemory|memoryStore|MemoryStore)\\b'), '长期记忆组件'),
      p(p0('\\b(?:recall|retrieve|load|fetch)_?memory\\b|memory\\s*[._]\\s*(?:recall|retrieve|save|store|persist|load|write|upsert)'), '记忆读写'),
      p(p0('\\b(?:remember|forget)\\s*\\(|\\b(?:fact|preference|lesson)s?_(?:store|table)'), '记忆写入语义'),
      p(p0('mem0|Mem0|letta|Letta|memgpt|MemGPT|zep|cognee'), '记忆框架'),
    ],
    docPatterns: [p(p0('长期记忆|记忆持久化|跨会话记忆|long-term memory'))],
    tags: ['Memory', 'Persistence'],
  },
  {
    id: 'context_management',
    label: '上下文管理',
    en: 'Context Compaction / Token Budget',
    category: 'memory',
    dimension: 'memory',
    weight: 8,
    headline: '在有限窗口内决定「保留什么、压缩什么、丢弃什么」，直接决定长任务能否跑完。',
    detail: '识别依据：显式 token 计数与预算、历史摘要压缩、截断/裁剪策略、上下文窗口常量。',
    patterns: [
      p(p0('\\b(?:countTokens|token_count|tokenCount|num_tokens|usage_metadata|estimateTokens|tiktoken)\\b'), 'Token 计数'),
      p(p0('\\b(?:compact|summariz|truncat|trim|prune|slid)(?:e|ing|ion|_history|_context)?\\b'), '压缩/裁剪'),
      p(p0('\\b(?:context_window|contextWindow|max_tokens|maxTokens|window_size|context_limit|token_budget|context_budget)\\b'), '窗口预算'),
      p(p0('context\\.get()|\\bclipContext\\b|\\btruncateMessages\\b'), '上下文装配'),
    ],
    docPatterns: [p(p0('上下文窗口|上下文压缩|token 预算|context rot|窗口管理'))],
    tags: ['Context', 'Token'],
  },
  {
    id: 'rag',
    label: 'RAG 检索增强生成',
    en: 'Retrieval-Augmented Generation',
    category: 'knowledge',
    dimension: 'knowledge',
    weight: 10,
    headline: '先从外部知识库召回相关片段，再交给模型生成，用于降低幻觉并接入私有知识。',
    detail: '识别依据：存在 retriever / retrieval 调用、top_k 召回参数、把检索结果拼进提示词的证据。',
    patterns: [
      p(p0('\\b(?:rag|retriev(?:e|er|al)|getRelevantDocuments|similarity_search|as_retriever)\\b'), '检索核心'),
      p(p0('\\b(?:top_k|topK|k=\\d+|n_results|limit=\\d+)\\b'), '召回数量'),
      p(p0('\\b(?:retrieved_documents|retrievedContext|context_documents|chunks?_for_prompt|evidence)\\b'), '召回结果注入'),
      p(p0('VectorStoreRetriever|Retriever|\\bretriever\\b'), '检索器类型'),
    ],
    docPatterns: [p(p0('\\bRAG\\b|检索增强|知识库问答|retrieval.augmented'))],
    tags: ['RAG', 'Retrieval'],
  },
  {
    id: 'vector_store',
    label: '向量检索与嵌入',
    en: 'Embedding & Vector Store',
    category: 'knowledge',
    dimension: 'knowledge',
    weight: 8,
    headline: '把文本编码为高维向量并用相似度召回，是 RAG 与语义记忆的底层引擎。',
    detail: '识别依据：embedding 模型调用、向量库客户端、余弦/点积相似度计算。',
    patterns: [
      p(p0('\\b(?:embed|embedding|embeddings|encode_query|embed_text|getEmbedding)\\b'), '嵌入调用'),
      p(p0('\\b(?:faiss|chroma|pinecone|qdrant|weaviate|milvus|pgvector|annoy|lancedb|supabase.*vector|hnsw)\\b'), '向量库'),
      p(p0('\\b(?:cosine|dot_product|dotProduct|euclidean|similarity|distance)[_ ]?(?:similarity|score|distance|search)?\\b'), '相似度计算'),
      p(p0('\\b(?:rerank|cross_encoder|crossEncoder|mmr|max_marginal)\\b'), '重排'),
    ],
    docPatterns: [p(p0('向量数据库|文本向量化|embedding 模型|相似度检索'))],
    tags: ['Embedding', 'Vector'],
  },
  {
    id: 'chunking',
    label: '文档切分',
    en: 'Chunking',
    category: 'knowledge',
    dimension: 'knowledge',
    weight: 6,
    headline: '把长文档切成带重叠的片段再入库，切分质量决定召回上限。',
    detail: '识别依据：chunk size / overlap 参数、递归或按标题切分逻辑。',
    patterns: [
      p(p0('\\b(?:chunk_size|chunkSize|chunk_overlap|chunkOverlap|split_text|splitDocuments|text_spliter|TextSplitter|MarkdownSplitter)\\b'), '切分参数'),
      p(p0('\\b(?:split|slice)_?(?:document|text|markdown|article)s?\\s*\\('), '切分函数'),
    ],
    docPatterns: [p(p0('分块|切分策略|chunk 策略|滑动窗口切分'))],
    tags: ['Chunking', 'Ingest'],
  },
  {
    id: 'tool_calling',
    label: '工具调用',
    en: 'Tool / Function Calling',
    category: 'tools',
    dimension: 'tools',
    weight: 10,
    headline: '把模型输出解析为结构化的函数调用并真正执行，是 Agent 从「会说」到「会做」的分界。',
    detail: '识别依据：工具注册表 / schema 声明、tool_calls 解析、按名称分发执行。',
    patterns: [
      p(p0('\\b(?:tool_calls|toolCalls|function_call|functionCall|tool_call)\\b'), '调用协议字段'),
      p(p0('\\b(?:registerTool|add_tool|@tool|tools?\\s*[:=]\\s*[\\[{]|ToolSpec|ToolDefinition|available_tools|availableTools|bind_tools|bindTools|TOOL_REGISTRY|tool_map|toolMap)\\b'), '工具注册'),
      p(p0('\\b(?:execute_tool|run_tool|call_tool|invoke_tool|runTool|callTool|invokeTool|dispatch_tool|dispatchTool|handle_tool_call)\\w*\\b'), '工具执行'),
      p(p0('\\btool\\s*\\.\\s*(?:run|invoke|execute)\\s*\\('), '工具调用点'),
      p(p0('\\binput_schema\\b|\\bparameters\\b\\s*:\\s*\\{|z\\.object\\s*\\(|\\bJsonSchema\\b|pydantic.*BaseModel'), '参数 Schema'),
    ],
    docPatterns: [p(p0('工具调用|function calling|function call|插件调用'))],
    tags: ['Tools', 'Function Calling'],
  },
  {
    id: 'mcp',
    label: 'MCP 协议接入',
    en: 'Model Context Protocol',
    category: 'tools',
    dimension: 'tools',
    weight: 7,
    headline: '用标准化协议把外部工具、资源与提示词暴露给模型，实现跨进程可插拔集成。',
    detail: '识别依据：MCP server/client 实现、tools/list 与 tools/call 方法、mcp.json 配置。',
    patterns: [
      p(p0('\\bmcp\\b|\\bMcp\\b|\\bMCP\\b|model.?context.?protocol'), 'MCP 标识'),
      p(p0('\\b(?:tools/list|tools/call|resources/list|prompts/list|CallToolResult|ListToolsResult)\\b'), 'MCP 方法'),
      p(p0('FastMCP|McpServer|McpClient|@mcp\\.tool'), 'MCP SDK'),
    ],
    docPatterns: [p(p0('Model Context Protocol|MCP 服务|MCP 工具'))],
    tags: ['MCP', 'Protocol'],
  },
  {
    id: 'planner',
    label: '任务规划与分解',
    en: 'Planner / Task Decomposition',
    category: 'reasoning',
    dimension: 'reasoning',
    weight: 9,
    headline: '把复杂目标拆成有序子任务再逐个执行，是长程任务成功率的主要来源。',
    detail: '识别依据：plan / steps / subtasks 数据结构、先规划后执行的编排、依赖图。',
    patterns: [
      p(p0('\\b(?:planner|plan_|_plan|\\bplan\\b|makePlan|create_plan|buildPlan|generatePlan)\\b'), '规划器'),
      p(p0('\\b(?:subtasks?|sub_goals?|subgoals?|steps?\\s*[:=]\\s*\\[|task_list|todo_list|todoList|task_graph|dependency)'), '子任务结构'),
      p(p0('\\b(?:decompos|orchestrat|dispatch_task|next_task|plan\\[)\\w*\\b'), '分解与调度'),
      p(p0('plan.and.solve|plan_and_solve|TreeOfThought|lotsofsteps'), '规划范式'),
    ],
    docPatterns: [p(p0('任务规划|任务拆解|子任务|计划生成|planning'))],
    tags: ['Planner', 'Decomposition'],
  },
  {
    id: 'reflection',
    label: '反思与自我纠错',
    en: 'Reflection / Self-Critique',
    category: 'reasoning',
    dimension: 'reasoning',
    weight: 8,
    headline: '让模型审视自己的输出并迭代修正，可显著提升复杂任务的正确率。',
    detail: '识别依据：critique/reflection/verify 环节、失败后带反馈重试、质量不达标重生成。',
    patterns: [
      p(p0('\\b(?:reflect|reflection|self_critique|selfCritique|critique|critic|review_output|evaluate_answer|refine|revise)\\b'), '反思环节'),
      p(p0('\\b(?:retry|attempt)s?\\b.*\\b(?:feedback|critique|error|hint)'), '带反馈重试'),
      p(p0('Reflexion|reflexion|self.refine|SelfRefine|verifier|Judge.*answer'), '反思范式'),
    ],
    docPatterns: [p(p0('反思|自我纠错|自我评估|critique|二次校验'))],
    tags: ['Reflection', 'Critique'],
  },
  {
    id: 'structured_output',
    label: '结构化输出',
    en: 'Structured Output / Schema',
    category: 'reasoning',
    dimension: 'architecture',
    weight: 8,
    headline: '强制模型按 JSON Schema 输出，下游代码才能稳定解析，而不是靠正则抢救。',
    detail: '识别依据：response_format / json_schema 声明、解析后校验、Pydantic/Zod 模型。',
    patterns: [
      p(p0('\\b(?:response_format|responseFormat|json_mode|jsonMode|function_calling_output|output_schema|outputSchema)\\b'), '输出格式约束'),
      p(p0('\\b(?:JSON.parse|json.loads|json_validate|safeParse|parse_obj|model_validate)\\b'), '解析'),
      p(p0('\\b(?:z\\.object|BaseModel|TypedDict|dataclass|pydantic|zod|io\\.github\\.classdef)\\b'), 'Schema 定义'),
    ],
    docPatterns: [p(p0('结构化输出|JSON 输出|schema 约束'))],
    tags: ['Schema', 'JSON'],
  },
  {
    id: 'multi_agent',
    label: '多智能体协作',
    en: 'Multi-Agent Orchestration',
    category: 'orchestration',
    dimension: 'architecture',
    weight: 8,
    headline: '多个角色化 Agent 分工、交接或投票，用职责隔离换取更高的单步可靠性。',
    detail: '识别依据：supervisor/handoff 编排、角色定义、Agent 之间互相调用或消息传递。',
    patterns: [
      p(p0('\\b(?:supervisor|orchestrator|handoff|hand_off|transfer_to|delegate|router_agent|agent_to_agent)\\b'), '编排交接'),
      p(p0('\\b(?:SubAgent|subagent|MultiAgent|multi_agent|Swarm|CrewAI|crew|autogen|agentscope|langgraph.*graph|GraphBuilder)\\b'), '多智能体框架'),
      p(p0('\\b(?:role|agent_name|agentName)\\s*[:=]\\s*[\'"][a-z_ ]{2,30}[\'"]\\s*,[\\s\\S]{0,200}\\b(?:system_prompt|systemPrompt|instructions)'), '角色定义'),
    ],
    docPatterns: [p(p0('多智能体|multi.agent|角色分工|协作编排'))],
    tags: ['Multi-Agent', 'Orchestration'],
  },
  {
    id: 'state_graph',
    label: '状态机 / 工作流图',
    en: 'Workflow Graph / State Machine',
    category: 'orchestration',
    dimension: 'architecture',
    weight: 6,
    headline: '用节点和边显式描述流程，把「模型自由发挥」约束在可审计的轨道内。',
    detail: '识别依据：node/edge 声明、状态转移、条件分支路由。',
    patterns: [
      p(p0('\\b(?:add_node|add_edge|add_conditional_edges|StateGraph|workflow\\.add|\\.compile\\s*\\()\\b'), '图构建'),
      p(p0('\\b(?:state_machine|StateMachine|transitions?\\s*[:=]|next_state|current_state)\\b'), '状态转移'),
      p(p0('\\b(?:n8n|dify|flowise|coze|langgraph|Airflow|Temporal)[\\w.]*\\b'), '工作流引擎'),
    ],
    docPatterns: [p(p0('工作流|状态机|流程图|DAG'))],
    tags: ['Workflow', 'Graph'],
  },
  {
    id: 'guardrails',
    label: '输入输出护栏',
    en: 'Guardrails',
    category: 'safety',
    dimension: 'safety',
    weight: 9,
    headline: '在进入模型前后做校验与拦截，防止注入、越权、泄漏和不合规内容。',
    detail: '识别依据：输入校验、输出审核、敏感词/注入检测、权限白名单。',
    patterns: [
      p(p0('\\b(?:guardrail|guard_rails|Guardrails|safety_check|moderation|content_filter|blocklist|allowlist|whitelist|blacklist)\\b'), '护栏组件'),
      p(p0('\\b(?:prompt_injection|injection|jailbreak|pii|redact|sanitiz|mask_|desensitiz)\\w*\\b'), '风险检测'),
      p(p0('\\b(?:validate_input|validateInput|validateOutput|checkPermission|authorize|permission_denied)\\b'), '校验与授权'),
    ],
    docPatterns: [p(p0('护栏|安全过滤|注入防护|敏感信息脱敏|权限校验'))],
    tags: ['Guardrails', 'Safety'],
  },
  {
    id: 'human_in_loop',
    label: '人工介入',
    en: 'Human-in-the-loop',
    category: 'safety',
    dimension: 'safety',
    weight: 6,
    headline: '高风险动作前暂停等待人确认，是自动化与可控性之间的关键阀门。',
    detail: '识别依据：approval / confirm / interrupt 语义、待人工审核队列。',
    patterns: [
      p(p0('\\b(?:human_input|humanInput|require_approval|requireApproval|await_approval|confirm_|user_confirm|userConfirm|interrupt_before|interrupts)\\b'), '确认中断'),
      p(p0('\\b(?:approval|review_queue|feedback_loop|escalat)\\w*\\b'), '审核队列'),
    ],
    docPatterns: [p(p0('人工确认|人在环|human in the loop|审批'))],
    tags: ['HITL', 'Approval'],
  },
  {
    id: 'retry_resilience',
    label: '重试与容错',
    en: 'Retry / Backoff / Fallback',
    category: 'reliability',
    dimension: 'reliability',
    weight: 9,
    headline: '对限流与瞬时故障做指数退避重试、超时控制和降级模型，决定线上可用性。',
    detail: '识别依据：retry/backoff 实现、timeout 设置、fallback 模型链、熔断。',
    patterns: [
      p(p0('\\b(?:retry|retries|backoff|exponential|tenacity|withRetry|retryAsync)\\b'), '重试'),
      p(p0('\\b(?:timeout|AbortController|withTimeout|asyncio\\.wait_for|deadline)\\b'), '超时'),
      p(p0('\\b(?:fallback|circuit_breaker|circuitBreaker|degrade|fallback_model|fallbackModel)\\b'), '降级熔断'),
    ],
    docPatterns: [p(p0('重试|退避|超时|降级|熔断|容错'))],
    tags: ['Retry', 'Resilience'],
  },
  {
    id: 'model_routing',
    label: '多模型路由',
    en: 'Model Routing',
    category: 'reliability',
    dimension: 'reliability',
    weight: 6,
    headline: '按任务难度、成本或可用性在不同模型间切换，兼顾质量与开销。',
    detail: '识别依据：多个模型标识、路由选择逻辑、provider 抽象层。',
    patterns: [
      p(p0('\\b(?:router|route_model|modelRouter|select_model|selectModel|pick_model|model_for)\\b'), '路由'),
      p(p0('\\b(?:gpt-[45o][\\w.\\-]*|claude-[\\w.\\-]+|deepseek-[\\w.\\-]+|qwen[\\w.\\-]*|gemini-[\\w.\\-]+|llama[\\w.\\-]*|moonshot|kimi)[\'"`]'), '多模型标识'),
      p(p0('\\b(?:ModelProvider|LLMProvider|provider_registry|create_model|init_chat_model)\\b'), 'Provider 抽象'),
    ],
    docPatterns: [p(p0('模型路由|多模型|模型切换|降级模型'))],
    tags: ['Routing', 'Provider'],
  },
  {
    id: 'streaming',
    label: '流式输出',
    en: 'Streaming',
    category: 'delivery',
    dimension: 'architecture',
    weight: 5,
    headline: '逐 token 推送结果，把首字延迟从秒级降到百毫秒级。',
    detail: '识别依据：stream 开关、SSE 响应、异步生成器逐块产出。',
    patterns: [
      p(p0('\\b(?:stream\\s*[:=]\\s*true|streaming|astream|iter_events|EventSource|text/event-stream|ReadableStream|flush\\s*\\()\\b'), '流式实现'),
      p(p0('\\b(?:yield|await?generator)\\b.*\\b(?:token|chunk|delta)\\b'), '逐块产出'),
    ],
    docPatterns: [p(p0('流式|打字机|SSE|增量输出'))],
    tags: ['Streaming', 'UX'],
  },
  {
    id: 'prompt_management',
    label: '提示词工程化管理',
    en: 'Prompt Management',
    category: 'reasoning',
    dimension: 'reasoning',
    weight: 7,
    headline: '提示词独立成文件/模板并版本化，可复用、可 diff、可回归测试。',
    detail: '识别依据：外置 prompt 文件、模板变量、few-shot 示例、版本或 hash 记录。',
    patterns: [
      p(p0('\\b(?:system_prompt|systemPrompt|SYSTEM_PROMPT|PROMPT_TEMPLATE|promptTemplate|load_prompt|loadPrompt|getPrompt|render_prompt|renderPrompt|prompt_path|promptRegistry|prompt_version|promptVersion)\\b'), '模板管理'),
      p(p0('\\b(?:few_shot|fewShot|few-shot|examples\\s*[:=]\\s*\\[|demonstrations)'), 'Few-shot'),
      p(p0('promptfoo|PromptTemplate|ChatPromptTemplate|jinja2|mustache|Handlebars|prompts/[\\w.]+'), '模板引擎'),
    ],
    docPatterns: [p(p0('提示词模板|prompt 版本|few-shot 示例|系统提示词'))],
    tags: ['Prompt', 'Template'],
  },
  {
    id: 'observability',
    label: '链路追踪与可观测',
    en: 'Tracing / Observability',
    category: 'observability',
    dimension: 'observability',
    weight: 8,
    headline: '记录每一步的输入输出、耗时与 token，出问题时能定位到具体环节。',
    detail: '识别依据：trace/span 结构、埋点上报、耗时与 token 统计、日志。',
    patterns: [
      p(p0('\\b(?:trace|tracing|span|startSpan|recordStep|TraceCollector|otel|opentelemetry|langsmith|langfuse|phoenix|arize|helicone)\\b'), '追踪'),
      p(p0('\\b(?:latency|duration_ms|elapsed|performance\\.now|time\\(\\)|Date\\.now|token_usage|usage\\s*[:=])\\b'), '指标采集'),
      p(p0('\\b(?:logger|logging|console\\.info|structlog|winston)\\w*\\b'), '日志'),
    ],
    docPatterns: [p(p0('链路追踪|可观测|埋点|监控指标'))],
    tags: ['Trace', 'Metrics'],
  },
  {
    id: 'evaluation',
    label: '评测与回归',
    en: 'Evaluation / Evals',
    category: 'observability',
    dimension: 'observability',
    weight: 8,
    headline: '用数据集和评分器量化每次改动的影响，避免「凭感觉调 Prompt」。',
    detail: '识别依据：评测集、指标计算、LLM/规则裁判、回归门禁。',
    patterns: [
      p(p0('\\b(?:evaluat|\\bevals?\\b|benchmark|golden_set|goldenSet|dataset|test_case|testCase|ground_truth|expected_output|expectedOutput)\\b'), '评测数据'),
      p(p0('\\b(?:llm_judge|llmJudge|rule_judge|RuleJudge|score_case|accuracy|pass_rate|passRate|recall_at|precision)\\b'), '打分'),
      p(p0('\\b(?:regression|release_gate|releaseGate|baseline|threshold)\\b'), '回归门禁'),
    ],
    docPatterns: [p(p0('评测|评估指标|基准测试|回归测试|打分器'))],
    tags: ['Evals', 'Regression'],
  },
  {
    id: 'caching',
    label: '缓存',
    en: 'Caching',
    category: 'reliability',
    dimension: 'reliability',
    weight: 5,
    headline: '对重复的模型调用或检索结果做缓存，降低成本并稳定延迟。',
    detail: '识别依据：prompt/response cache、语义缓存、LRU 结构。',
    patterns: [
      p(p0('\\b(?:cache|Cache|lru_cache|LRUCache|memoize|redis|memcached)\\b'), '缓存组件'),
      p(p0('\\b(?:semantic_cache|semanticCache|prompt_cache|promptCache|response_cache|cache_key)\\b'), 'LLM 缓存'),
    ],
    docPatterns: [p(p0('缓存|命中|去重'))],
    tags: ['Cache', 'Cost'],
  },
  {
    id: 'concurrency',
    label: '并发与批处理',
    en: 'Concurrency / Parallel Execution',
    category: 'reliability',
    dimension: 'reliability',
    weight: 5,
    headline: '并行执行独立子任务或工具调用，把串行等待时间压缩掉。',
    detail: '识别依据：并发原语、任务队列、worker pool、批量提交。',
    patterns: [
      p(p0('\\b(?:Promise\\.all|Promise\\.allSettled|asyncio\\.gather|concurrent\\.futures|ThreadPool|goroutine|go func|tokio::spawn|Worker|pmap|queue)\\b'), '并发原语'),
      p(p0('\\b(?:batch|bulk|semaphore|mutex|lock\\(|rate_limit|rateLimit|concurrenc)\\w*\\b'), '调度与限流'),
    ],
    docPatterns: [p(p0('并发|并行|批量|队列|限流'))],
    tags: ['Async', 'Batch'],
  },
  {
    id: 'cost_control',
    label: '成本与用量控制',
    en: 'Cost Control',
    category: 'reliability',
    dimension: 'reliability',
    weight: 6,
    headline: '统计每次调用的 token 与金额并设预算上限，防止失控账单。',
    detail: '识别依据：usage 聚合、单价表、成本字段、预算判断。',
    patterns: [
      p(p0('\\b(?:cost|price_per|pricing|total_cost|estimated_cost|usage_cost|billing)\\b'), '成本字段'),
      p(p0('\\b(?:prompt_tokens|completion_tokens|total_tokens|input_tokens|output_tokens)\\b'), '用量统计'),
      p(p0('\\b(?:budget|spend_limit|quota)\\b'), '预算控制'),
    ],
    docPatterns: [p(p0('成本|费用|token 用量|预算'))],
    tags: ['Cost', 'Usage'],
  },
  {
    id: 'code_execution',
    label: '代码执行沙箱',
    en: 'Code Execution / Sandbox',
    category: 'tools',
    dimension: 'tools',
    weight: 5,
    headline: '让 Agent 写代码并真实运行，能力上限极高，因此隔离与资源限制是必备前提。',
    detail: '识别依据：exec/eval/subprocess、docker 沙箱、超时与内存限制。',
    patterns: [
      p(p0('\\b(?:exec\\s*\\(|eval\\s*\\(|subprocess|child_process|execSync|spawn|vm\\.runInNewContext|Interpreter|sandbox|docker run|e2b|pyodide)\\b'), '执行入口'),
      p(p0('\\b(?:rlimit|memory_limit|cpu_limit|network_disabled|read_only|jail)\\b'), '隔离限制'),
    ],
    docPatterns: [p(p0('代码执行|沙箱|运行代码|解释器'))],
    tags: ['Sandbox', 'Code'],
  },
  {
    id: 'web_access',
    label: '联网与浏览器操作',
    en: 'Web / Browser Access',
    category: 'tools',
    dimension: 'tools',
    weight: 5,
    headline: '抓取网页或驱动浏览器，把 Agent 的能力扩展到实时信息。',
    detail: '识别依据：http 请求、爬虫、headless 浏览器驱动。',
    patterns: [
      p(p0('\\b(?:requests\\.(?:get|post)|fetch\\s*\\(|axios|httpx|urllib|got\\s*\\(|WebClient|crawl|scrape|BeautifulSoup|cheerio|http_fetch|fetch_url|fetchUrl|web_fetch|webSearch|web_search)\\b'), 'HTTP 抓取'),
      p(p0('\\b(?:playwright|puppeteer|selenium|undetected|browserless|headless)\\b'), '浏览器驱动'),
    ],
    docPatterns: [p(p0('联网|抓取|爬虫|浏览器自动化|实时搜索'))],
    tags: ['Web', 'Browser'],
  },
  {
    id: 'filesystem_access',
    label: '文件系统与持久化',
    en: 'Filesystem & Persistence',
    category: 'tools',
    dimension: 'tools',
    weight: 4,
    headline: '读写本地文件或数据库，让 Agent 产出真实可用的工件。',
    detail: '识别依据：fs/open 读写、sqlite/postgres 客户端、对象存储。',
    patterns: [
      p(p0('\\b(?:readFileSync|writeFileSync|fs\\.(?:read|write|append)|open\\s*\\(|Path\\(|pathlib|shutil|os\\.path)\\b'), '文件读写'),
      p(p0('\\b(?:sqlite3|better-sqlite3|postgres|mysql|prisma|drizzle|sqlalchemy|mongoose|redis|s3|boto3)\\b'), '存储客户端'),
    ],
    docPatterns: [p(p0('文件读写|持久化|数据库'))],
    tags: ['FS', 'DB'],
  },
  {
    id: 'multimodal',
    label: '多模态输入',
    en: 'Multimodal',
    category: 'delivery',
    dimension: 'architecture',
    weight: 4,
    headline: '处理图片、音频、视频等非文本输入，扩展可自动化任务的范围。',
    detail: '识别依据：image/audio/vision 内容块、base64 媒体、ASR/TTS。',
    patterns: [
      p(p0('\\b(?:vision|image_url|base64|multipart|audio|transcribe|asr|tts|whisper|ocr|screenshot|image_block)\\b'), '媒体处理'),
    ],
    docPatterns: [p(p0('多模态|图片理解|语音识别|文字识别'))],
    tags: ['Vision', 'Audio'],
  },
  {
    id: 'failure_taxonomy',
    label: '失败归因分类',
    en: 'Failure Classification',
    category: 'observability',
    dimension: 'observability',
    weight: 6,
    headline: '把失败分成可统计的类别（检索错、工具错、格式错…），优化才有靶子。',
    detail: '识别依据：失败类型枚举、归因逻辑、错误码映射。',
    patterns: [
      p(p0('\\b(?:failure_type|failureType|error_code|errorCode|FailureClass|classify_failure|classifyFailure|root_cause|rootCause)\\b'), '归因'),
      p(p0('\\b(?:invalid_arguments|tool_error|timeout_error|hallucination|refusal|truncated)\\b'), '失败类别'),
    ],
    docPatterns: [p(p0('失败归因|错误分类|根因分析'))],
    tags: ['Failure', 'RCA'],
  },
  {
    id: 'session_isolation',
    label: '会话与身份隔离',
    en: 'Session & Identity Scoping',
    category: 'safety',
    dimension: 'safety',
    weight: 5,
    headline: '按用户/会话隔离记忆与权限，防止跨用户数据串味。',
    detail: '识别依据：session_id / user_id 贯穿传参、命名空间隔离。',
    patterns: [
      p(p0('\\b(?:session_id|sessionId|user_id|userId|tenant_id|namespace|scope_id|thread_id|threadId)\\b'), '标识作用域'),
    ],
    docPatterns: [p(p0('会话隔离|多租户|用户身份'))],
    tags: ['Session', 'Isolation'],
  },
  {
    id: 'api_surface',
    label: '服务化接口',
    en: 'API / Service Surface',
    category: 'delivery',
    dimension: 'architecture',
    weight: 4,
    headline: '把 Agent 暴露为 HTTP/CLI 服务，才能被其它系统集成调用。',
    detail: '识别依据：路由注册、服务监听、命令行入口。',
    patterns: [
      p(p0('\\b(?:app\\.(?:get|post|route)|router\\.(?:get|post)|FastAPI|Express|createServer|listen\\s*\\(|@RestController|actix_web)\\b'), 'HTTP 服务'),
      p(p0('\\b(?:argparse|click\\.command|commander|yargs|inquirer|readline)\\b'), 'CLI 入口'),
    ],
    docPatterns: [p(p0('接口|服务化|命令行工具|部署'))],
    tags: ['API', 'CLI'],
  },
];

function p0(source) {
  return source.replace(/\\\\/g, '\\');
}
